Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../setup", "/tmp/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
      #pacman -Syu --noconfirm
      #systemctl enable rngd; systemctl start rngd
      #cat /tmp/vagrant/hosts >> /etc/hosts
  SHELL

end
