Vagrant.configure("2") do |config|
  #config.vm.box = "archlinux/archlinux"
  #config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../build-scripts", "/home/vagrant/build-scripts", type: "rsync"
  #config.vm.provision "shell", inline: <<-SHELL
      #pacman -Syu --noconfirm
      #systemctl enable rngd; systemctl start rngd
      #cat /tmp/vagrant/hosts >> /etc/hosts
	  #cd /tmp/vagrant/scripts
  #SHELL
  config.disksize.size = '20GB'
  config.vm.define "build-rpi-armv7" do |build|
    build.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
	  vb.cpus = 2
	  #vb.disksize.size = '30GB'
    end
    build.vm.provision "shell", inline: <<-SHELL
        echo "yarp"
		#pacman -Syu
		#pacman -S parted git base-devel qemu qemu-arch-extra --noconfirm
		apt-get update && apt-get -y install rng-tools qemu qemu-user-static binfmt-support parted wget dosfstools zip systemd-container
    	/bin/bash build-scripts/create-image
		echo "If everything worked, you can execute:"
		echo "'vagrant scp build-rpi-armv7:/home/vagrant/pifrob-rpi-2-arm.img .'" 
		echo "to copy to your local machine."
    SHELL
  end
end
